all:
#	pandoc La\ Torre\ del\ Estratega.md -o La\ Torre\ del\ Estratega.pdf --pdf-engine=xelatex -V geometry:"a4paper, margin=1.5cm" -V classoption=twocolumn
	pandoc La\ Torre\ del\ Estratega.md -o La\ Torre\ del\ Estratega.pdf --pdf-engine=xelatex -V geometry:"a4paper, margin=1.5cm"

